remote_theme: pages-themes/dinky@v0.2.0
title: This video is sponsored by ADA! An analysis of sponsorships on YouTube
description: A template website for ADA
show_downloads: False
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
