theme: jekyll-theme-minimal
title: This video is sponsored by ADA! An analysis of sponsorships on YouTube
description: A template website for ADA
show_downloads: True
remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
